## Configuracion de Instancia
server:
  port: 8088
  error:
    include-stacktrace: on_param

## Configuracion del cliente de Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: ms-multa

## Configuracion de Spring
spring:
  application:
    name: ms-multa
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true


## Configuracion secundaria (custom)
getPropietario:
  url: http://ms-propietario/propietario/%s
