## Configuracion de Instancia
server:
  port: 8084
  error:
    include-stacktrace: on_param

## Configuracion del cliente de Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: ms-presupuesto

## Configuracion de Spring
spring:
  application:
    name: ms-presupuesto
  datasource:
    url: jdbc:postgresql://localhost:5432/residencia
    username: postgres
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
